# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1b726lvISiFilwfehxnwMkziCEh6_8I
"""

import matplotlib.pyplot as plt

n=[10000,20000,30000,40000,50000,60000]
Iterative_Insertion=[0.004,0.01,0.011,0.016,0.023,0.029]
Recursive_Insertion=[0.007,0.011,0.018,0.028,0.03,0.032]

plt.plot(n, Iterative_Insertion, marker='o', label='Binary_Tree_Insertion_Iterative')
plt.plot(n, Recursive_Insertion, marker='o', label='Binary_Tree_Insertion_Recursive')


plt.xlabel('Array Size (n)')
plt.ylabel('Time (seconds)')
plt.title('Algorithm Performance Comparison')
plt.legend()
plt.grid(True)

plt.show()